### ISSUE TITLE
`date_histogram` Elasticsearch v8 changes

### ISSUE THREAD

**Issue by dubiousdavid** [smartprocure/contexture#113]
`interval` is no longer supported for `date_histogram` in Elasticsearch v8.

https://github.com/smartprocure/contexture/blob/main/packages/provider-elasticsearch/src/example-types/metricGroups/dateIntervalGroupStats.js#L74

![date-histogram](https://github.com/smartprocure/contexture/assets/1327969/b57cbc4c-016a-4e65-881b-30c316b90d53)

**Comment by daedalus28** [comment]
Fixed by #120
