### ISSUE TITLE
Issue Migration

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture#5]
Let's check the old repos' remaining issues/branches for issues to open here. We can consolidate many now that we're all fancy with a monorepo (for example, documentation issues) and some can probably be dropped.

- [ ] [client](https://github.com/smartprocure/contexture-client)
- [ ] [export](https://github.com/smartprocure/contexture-export)
- [ ] [provider-elasticsearch](https://github.com/smartprocure/contexture-elasticsearch)
- [ ] [provider-mongo](https://github.com/smartprocure/contexture-mongo)
- [ ] [react](https://github.com/smartprocure/contexture-react)
- [ ] [server](https://github.com/smartprocure/contexture-core)

We can structure some of this in a roadmap issue to track the plans we have for each package.

**Comment by positiveVibes4all** [comment]
Closing this as the migration task has been completed to a mono repo.
